name: smart_home_firebase
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  cloud_firestore: ^4.7.15

  google_fonts: 5.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  fluttertoast: ^8.2.5
  flutter_bluetooth_serial: ^0.4.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
