// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQncYFZ1rWh05ccc0PXYomT88OzFakwpg',
    appId: '1:247811437922:web:a5fc9cfad5899bb62ca83b',
    messagingSenderId: '247811437922',
    projectId: 'smart-home-e7547',
    authDomain: 'smart-home-e7547.firebaseapp.com',
    storageBucket: 'smart-home-e7547.appspot.com',
    measurementId: 'G-PE1N4D3R05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfvLEbv-c0M9lB5c9EIrIYxRoe9Wc9EMw',
    appId: '1:247811437922:android:74d1ad27e8ba4a702ca83b',
    messagingSenderId: '247811437922',
    projectId: 'smart-home-e7547',
    storageBucket: 'smart-home-e7547.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9RFXHZWN0QPYdI5PD3k7hSEvhxJiwVE',
    appId: '1:247811437922:ios:a068da2a88194ca12ca83b',
    messagingSenderId: '247811437922',
    projectId: 'smart-home-e7547',
    storageBucket: 'smart-home-e7547.appspot.com',
    iosBundleId: 'com.example.smartHomeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz9RFXHZWN0QPYdI5PD3k7hSEvhxJiwVE',
    appId: '1:247811437922:ios:a068da2a88194ca12ca83b',
    messagingSenderId: '247811437922',
    projectId: 'smart-home-e7547',
    storageBucket: 'smart-home-e7547.appspot.com',
    iosBundleId: 'com.example.smartHomeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQncYFZ1rWh05ccc0PXYomT88OzFakwpg',
    appId: '1:247811437922:web:f11439c403520d342ca83b',
    messagingSenderId: '247811437922',
    projectId: 'smart-home-e7547',
    authDomain: 'smart-home-e7547.firebaseapp.com',
    storageBucket: 'smart-home-e7547.appspot.com',
    measurementId: 'G-B5GDNF5Y6L',
  );
}
